// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWzhvrfFIzvpRFlaShtYiNiS1Pmv5qAZY',
    appId: '1:753895232080:web:b572332e873bf5d4563755',
    messagingSenderId: '753895232080',
    projectId: 'gccabo',
    authDomain: 'gccabo.firebaseapp.com',
    storageBucket: 'gccabo.firebasestorage.app',
    measurementId: 'G-G981F79Y7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsUio7w7DoQhSvm_aqrCeneQACQ5ZiUnE',
    appId: '1:753895232080:android:125ca0c938c67003563755',
    messagingSenderId: '753895232080',
    projectId: 'gccabo',
    storageBucket: 'gccabo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAOArEImtr98k7e0tgHnc_3IV2Sc1Ag-0',
    appId: '1:753895232080:ios:9cbac0874ea0abc0563755',
    messagingSenderId: '753895232080',
    projectId: 'gccabo',
    storageBucket: 'gccabo.firebasestorage.app',
    iosBundleId: 'com.moreausoft.gccabo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAOArEImtr98k7e0tgHnc_3IV2Sc1Ag-0',
    appId: '1:753895232080:ios:9cbac0874ea0abc0563755',
    messagingSenderId: '753895232080',
    projectId: 'gccabo',
    storageBucket: 'gccabo.firebasestorage.app',
    iosBundleId: 'com.moreausoft.gccabo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWzhvrfFIzvpRFlaShtYiNiS1Pmv5qAZY',
    appId: '1:753895232080:web:a0681126ff3b81d0563755',
    messagingSenderId: '753895232080',
    projectId: 'gccabo',
    authDomain: 'gccabo.firebaseapp.com',
    storageBucket: 'gccabo.firebasestorage.app',
    measurementId: 'G-LECZKRF5PN',
  );

}